### ISSUE TITLE
publish-java action has never been run, bindings are not in Maven

### ISSUE THREAD

**Issue by bromls** [microsoft/regorus#237]
The documentation in `README.md` and in `bindings/java/README.md` indicates that Java bindings for `regorus` are published to Maven Central. I don’t see the bindings in Maven, and the GitHub action for making this true appears to have never been run: https://github.com/microsoft/regorus/actions/workflows/publish-java.yml

**Comment by anakrish** [comment]
@bromls This is a documentation issue. CC @unexge, the owner of the Java binding.

As noted in the [bindings](https://github.com/microsoft/regorus?tab=readme-ov-file#bindings), we currently don't publish bindings to repositories due to the operational overhead.
However, I have been collecting use cases to help justify the cost of publishing the bindings. Would it be possible to share your use case?

**Comment by anakrish** [comment]
Addressed by #246
